# Generated by Django 4.1.4 on 2022-12-16 12:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('_id', models.CharField(db_column='id', default=uuid.UUID('8f3ad004-dc9e-4f10-8663-68e8ec4ea13c'), max_length=40, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(max_length=255, unique=True)),
                ('ctime', models.DateTimeField(verbose_name='注册时间')),
                ('utime', models.DateTimeField(verbose_name='最后一次更新时间')),
                ('reg_reason', models.CharField(default='自动发现并注册', max_length=1024, verbose_name='注册方式')),
                ('oper_id', models.CharField(max_length=40, verbose_name='操作人员ID')),
                ('remarks', models.TextField(default='一般操作', verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(default='--', max_length=40, verbose_name="代理工具ID(当该项为模板时,值为'--')")),
                ('path', models.FilePathField(verbose_name='配置文件路径')),
                ('section', models.CharField(max_length=255, verbose_name='配置段')),
                ('key', models.CharField(max_length=255, verbose_name='配置键')),
                ('value', models.CharField(max_length=1024, verbose_name='配置值')),
                ('ctime', models.DateTimeField(verbose_name='创建时间')),
                ('utime', models.DateTimeField(verbose_name='更新时间')),
                ('oper_id', models.CharField(max_length=40, verbose_name='操作人ID')),
                ('remarks', models.TextField(default='一般操作。', verbose_name='备注')),
                ('is_template', models.BooleanField(default=False, verbose_name='是否为模板字段')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigTemplate',
            fields=[
                ('_id', models.UUIDField(db_column='id', default=uuid.UUID('611df845-aaff-4aab-893f-93e6add79dcd'), primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('owner_id', models.CharField(max_length=40, verbose_name='拥有者ID')),
                ('path', models.FilePathField(verbose_name='配置文件路径')),
                ('salt', models.CharField(max_length=1024, verbose_name='Slat(AES加密)')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('_id', models.CharField(db_column='id', default=uuid.UUID('bfee8252-0138-44d2-af3a-0eaa7f71a8ad'), max_length=40, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='组名')),
                ('synopsis', models.TextField(blank=True, verbose_name='简介')),
                ('ctime', models.DateTimeField(verbose_name='创建时间')),
                ('utime', models.DateTimeField(verbose_name='更新时间')),
                ('gid', models.CharField(max_length=40, verbose_name='GID')),
            ],
        ),
        migrations.CreateModel(
            name='LogItem',
            fields=[
                ('_id', models.UUIDField(db_column='id', default=uuid.UUID('0692f050-0a35-4d97-8984-639c1258ee87'), primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='操作内容')),
                ('oper_id', models.CharField(max_length=40, verbose_name='操作人ID')),
                ('ctime', models.DateTimeField(verbose_name='操作时间')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('_id', models.CharField(db_column='id', default=uuid.UUID('48cd4acb-d387-4d2c-9be1-ea56f0a1b552'), max_length=40, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='姓名')),
                ('no', models.CharField(max_length=128, verbose_name='工号')),
                ('domain', models.CharField(max_length=1024, verbose_name='组织架构路径')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码(AES加密)')),
                ('email', models.EmailField(max_length=255, verbose_name='工作邮箱')),
                ('email_backup', models.EmailField(max_length=255, verbose_name='备用工作邮箱')),
                ('phone', models.CharField(max_length=255, verbose_name='工作手机')),
                ('ctime', models.DateTimeField(verbose_name='创建时间')),
                ('utime', models.DateTimeField(verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='OperatorGroupRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_column='uid', max_length=40, verbose_name='UID')),
                ('gid', models.CharField(db_column='gid', max_length=40, verbose_name='GID')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceConfig',
            fields=[
                ('_id', models.CharField(db_column='id', default=uuid.UUID('9b203237-a77d-4590-b21b-1f45887e8f39'), max_length=40, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(blank=True, max_length=255)),
                ('ctime', models.DateTimeField(verbose_name='创建时间')),
                ('utime', models.DateTimeField(verbose_name='更新时间')),
            ],
        ),
    ]
