# Generated by Django 4.1.4 on 2022-12-16 12:36

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='_id',
            field=models.CharField(db_column='id', default=uuid.UUID('3d930354-a3c5-42b0-8c44-28371e35c629'), max_length=40, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='configtemplate',
            name='_id',
            field=models.UUIDField(db_column='id', default=uuid.UUID('32043209-eb07-4b2c-9988-dd9ca48a5049'), primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='group',
            name='_id',
            field=models.CharField(db_column='id', default=uuid.UUID('a3f1fc56-58a7-4bac-ae4d-d316df7391bf'), max_length=40, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='logitem',
            name='_id',
            field=models.UUIDField(db_column='id', default=uuid.UUID('a2f5a2bf-a290-4a35-aaad-de1abb1a785a'), primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='_id',
            field=models.CharField(db_column='id', default=uuid.UUID('9bb3ff4a-b15c-4bb5-8b69-00a3eb56ea70'), max_length=40, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='ctime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='serviceconfig',
            name='_id',
            field=models.CharField(db_column='id', default=uuid.UUID('1e2f3eef-9e51-46cb-8104-673e9aff15cd'), max_length=40, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='serviceconfig',
            name='cname',
            field=models.CharField(blank=True, max_length=255, verbose_name='别名'),
        ),
        migrations.AlterModelTable(
            name='operatorgroupref',
            table='t_operator_group_ref',
        ),
    ]
