# Generated by Django 4.1.4 on 2022-12-16 12:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_agent__id_alter_configtemplate__id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='_id',
            field=models.CharField(db_column='id', default=uuid.UUID('80a8b794-2e81-4c34-be65-728dd770e9b8'), max_length=40, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='configtemplate',
            name='_id',
            field=models.UUIDField(db_column='id', default=uuid.UUID('4794f390-8f7c-4526-9154-3a28abe4337e'), primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='group',
            name='_id',
            field=models.CharField(db_column='id', default=uuid.UUID('d5151724-29c7-4c12-ae13-c3d5fe20d601'), max_length=40, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='logitem',
            name='_id',
            field=models.UUIDField(db_column='id', default=uuid.UUID('6fcfe3d1-cc5c-4170-a6b9-db9b4221338d'), primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='_id',
            field=models.CharField(db_column='id', default=uuid.UUID('55edbcd2-7273-4856-a6da-df3c5e9c1fe5'), max_length=40, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='serviceconfig',
            name='_id',
            field=models.CharField(db_column='id', default=uuid.UUID('84e0996a-fa07-4df2-b13b-fd53b852205b'), max_length=40, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='agent',
            table='t_agent',
        ),
        migrations.AlterModelTable(
            name='config',
            table='t_config',
        ),
        migrations.AlterModelTable(
            name='configtemplate',
            table='t_config_template',
        ),
        migrations.AlterModelTable(
            name='group',
            table='t_group',
        ),
        migrations.AlterModelTable(
            name='logitem',
            table='t_log_item',
        ),
        migrations.AlterModelTable(
            name='operator',
            table='t_operator',
        ),
        migrations.AlterModelTable(
            name='serviceconfig',
            table='t_server_config',
        ),
    ]
