# Generated by Django 4.1.4 on 2022-12-16 14:31

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_agent__id_alter_configtemplate__id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='gid',
        ),
        migrations.AlterField(
            model_name='agent',
            name='_id',
            field=models.CharField(db_column='id', default=uuid.uuid4, max_length=40, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='ctime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='config',
            name='ctime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='config',
            name='path',
            field=models.TextField(verbose_name='配置文件路径'),
        ),
        migrations.AlterField(
            model_name='config',
            name='utime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='configtemplate',
            name='_id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='configtemplate',
            name='path',
            field=models.TextField(verbose_name='配置文件路径'),
        ),
        migrations.AlterField(
            model_name='group',
            name='_id',
            field=models.CharField(db_column='id', default=uuid.uuid4, max_length=40, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='group',
            name='ctime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='group',
            name='utime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='logitem',
            name='_id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='_id',
            field=models.CharField(db_column='id', default=uuid.uuid4, max_length=40, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='utime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='serviceconfig',
            name='_id',
            field=models.CharField(db_column='id', default=uuid.uuid4, max_length=40, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='serviceconfig',
            name='ctime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='serviceconfig',
            name='utime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间'),
        ),
    ]
